MedicalCenterRegistration/Models/Patient.cs
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using MedicalCenterRegistration.Enums;
using MedicalCenterRegistration.Validation;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;

namespace MedicalCenterRegistration.Models
{
    public class Patient
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Imię jest wymagane.")]
        [StringLength(100, MinimumLength = 1)]
        [DisplayName("Imię")]
        public required string Name { get; set; }

        [Required(ErrorMessage = "Nazwisko jest wymagane.")]
        [StringLength(100, MinimumLength = 1)]
        [DisplayName("Nazwisko")]
        public required string LastName { get; set; }

        [Required(ErrorMessage = "Numer telefonu jest wymagany.")]
        [Phone(ErrorMessage = "Nieprawidłowy numer telefonu. Wprowadź poprawny numer telefonu.")]
        [DisplayName("Numer telefonu")]
        public string PhoneNumber { get; set; }

        [Required(ErrorMessage = "Pesel jest wymagany.")]
        [RegularExpression(@"^[0-9]{11}$", ErrorMessage = "Numer PESEL musi składać się z 11 cyfr.")]
        [DisplayName("Numer PESEL")]
        public string PeselNumber { get; set; }

        [Required(ErrorMessage = "Data urodzenia jest wymagana.")]
        [DataType(DataType.Date)]
        [MinYearsInThePast(18, ErrorMessage = "Pacjent musi mieć minimum 18 lat.")]
        [DisplayName("Data urodzenia")]
        public DateTime DateOfBirth { get; set; }

        [Required(ErrorMessage = "Płeć jest wymagana.")]
        [EnumDataType(typeof(Sex), ErrorMessage = "Nieprawidłowa płeć.")]
        [DisplayName("Płeć")]
        public Sex Sex { get; set; }

        // ADDRESS DATA

        [Required(ErrorMessage = "Ulica jest wymagana.")]
        [StringLength(100, MinimumLength = 1)]
        [DisplayName("Ulica")]
        public string Street { get; set; }

        [Required(ErrorMessage = "Numer domu jest wymagany.")]
        [StringLength(10, MinimumLength = 1)]
        [DisplayName("Numer domu")]
        public string HouseNumber { get; set; }

        [Required(ErrorMessage = "Województwo jest wymagane.")]
        [StringLength(100, MinimumLength = 1)]
        [DisplayName("Województwo")]
        public string Province { get; set; }

        [Required(ErrorMessage = "Powiat mieszkania jest wymagany.")]
        [StringLength(100, MinimumLength = 1)]
        [DisplayName("Powiat")]
        public string District { get; set; }

        [Required(ErrorMessage = "Kod pocztowy jest wymagany.")]
        [RegularExpression(@"^\d{2}-\d{3}$", ErrorMessage = "Nieprawidłowy kod pocztowy. Wprowadź kod w formacie XX-XXX.")]
        [DisplayName("Kod pocztowy")]
        public string PostalCode { get; set; }

        [Required(ErrorMessage = "Miejscowość jest wymagana.")]
        [StringLength(100, MinimumLength = 1)]
        [DisplayName("Miejscowość")]
        public string City { get; set; }


        // OTHER
        [ValidateNever]
        public string UserId { get; set; }
        public IdentityUser? User { get; set; }

        [DisplayName("Data utworzenia")]
        public DateTime CreatedAt { get; set; }

    }
}

MedicalCenterRegistration/Models/ViewModels/Patients/PatiensListViewModel.cs
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

namespace MedicalCenterRegistration.Models.ViewModels.Patients
{
    public enum PatientsTableMode
    {
        Default,
        SelectForVisit
    }

    public class PatiensListViewModel
    {
        public List<Patient> Patients = new();
        public string searchString = string.Empty;
        public PatientsTableMode mode = PatientsTableMode.Default;
    }
}

MedicalCenterRegistration/Models/ViewModels/Patients/PatientCardViewModel.cs
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using MedicalCenterRegistration.Enums;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace MedicalCenterRegistration.Models.ViewModels.Patients
{
    public class PatientCardViewModel
    {
        [Required(ErrorMessage = "Wybierz użytkownika.")]
        [DisplayName("Użytkownik z rolą pacjenta")]
        public string SelectedUserId { get; set; }

        public List<SelectListItem> AvailableUsers { get; set; } = new();

        [Required(ErrorMessage = "Imię jest wymagane.")]
        [StringLength(100, MinimumLength = 1)]
        [DisplayName("Imię")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Nazwisko jest wymagane.")]
        [StringLength(100, MinimumLength = 1)]
        [DisplayName("Nazwisko")]
        public string LastName { get; set; }

        [Required(ErrorMessage = "Numer telefonu jest wymagany.")]
        [Phone(ErrorMessage = "Nieprawidłowy numer telefonu.")]
        [DisplayName("Numer telefonu")]
        public string PhoneNumber { get; set; }

        [Required(ErrorMessage = "PESEL jest wymagany.")]
        [RegularExpression(@"^[0-9]{11}$", ErrorMessage = "PESEL musi mieć 11 cyfr.")]
        [DisplayName("PESEL")]
        public string PeselNumber { get; set; }

        [Required(ErrorMessage = "Data urodzenia jest wymagana.")]
        [DataType(DataType.Date)]
        [DisplayName("Data urodzenia")]
        public DateTime DateOfBirth { get; set; }

        [Required(ErrorMessage = "Płeć jest wymagana.")]
        [DisplayName("Płeć")]
        public Sex Sex { get; set; }

        [Required(ErrorMessage = "Ulica jest wymagana.")]
        [StringLength(100, MinimumLength = 1)]
        [DisplayName("Ulica")]
        public string Street { get; set; }

        [Required(ErrorMessage = "Numer domu jest wymagany.")]
        [DisplayName("Numer domu")]
        public string HouseNumber { get; set; }

        [Required(ErrorMessage = "Województwo jest wymagane.")]
        [StringLength(100, MinimumLength = 1)]
        [DisplayName("Województwo")]
        public string Province { get; set; }

        [Required(ErrorMessage = "Powiat jest wymagany.")]
        [StringLength(100, MinimumLength = 1)]
        [DisplayName("Powiat")]
        public string District { get; set; }

        [Required(ErrorMessage = "Kod pocztowy jest wymagany.")]
        [RegularExpression(@"^\d{2}-\d{3}$", ErrorMessage = "Nieprawidłowy kod pocztowy (XX-XXX).")]
        [DisplayName("Kod pocztowy")]
        public string PostalCode { get; set; }

        [Required(ErrorMessage = "Miejscowość jest wymagana.")]
        [StringLength(100, MinimumLength = 1)]
        [DisplayName("Miejscowość")]
        public string City { get; set; }
    }
}

MedicalCenterRegistration/Models/ViewModels/Patients/PatientInListViewModel.cs
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

namespace MedicalCenterRegistration.Models.ViewModels.Patients
{
    public enum PatientsTableMode
    {
        Default,
        SelectForVisit
    }

    public class PatientInListViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public object UserEmail { get; set; }
        public string CreatedAt { get; set; }

        public PatientsTableMode mode = PatientsTableMode.Default;
    }
}

MedicalCenterRegistration/Controllers/PatientsController.cs
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System.Security.Claims;
using MedicalCenterRegistration.Consts;
using MedicalCenterRegistration.Data;
using MedicalCenterRegistration.Enums;
using MedicalCenterRegistration.Helpers;

using MedicalCenterRegistration.Models;
using MedicalCenterRegistration.Models.ViewModels.Patients;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace MedicalCenterRegistration.Controllers
{
    public class PatientsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public PatientsController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }



        // GET: Patients
        [Authorize(Roles = Roles.AdminAndReceptionist)]
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            return View();
        }

        // POST: GetPatients
        [Authorize(Roles = Roles.AdminAndReceptionist)]
        [HttpPost]
        public async Task<IActionResult> GetPatients()
        {
            var query = _context.Patient.Include(p => p.User).AsQueryable();

            var request = DataTableHelper.GetRequest(Request);

            var totalRecords = await query.CountAsync();

            // filtering
            if (!string.IsNullOrEmpty(request.SearchValue))
            {
                var searchValue = request.SearchValue.ToLower();
                query = query.Where(p =>
                    p.Name.ToLower().Contains(searchValue.ToLower()) ||
                    p.LastName.ToLower().Contains(searchValue.ToLower()) ||
                    p.User.Email.ToLower().Contains(searchValue.ToLower())
                );
            }

            var filteredRecords = await query.CountAsync();

            // sorting
            query = query.ApplySorting(request);

            // paging
            var patients = await query
                .Skip(request.Start)
                .Take(request.Length)
                .ToListAsync();


            var patientsVm = new List<PatientInListViewModel>();
            foreach (var patient in patients)
            {
                patientsVm.Add(new PatientInListViewModel
                {
                    Id = patient.Id,
                    Name = patient.Name,
                    LastName = patient.LastName,
                    UserEmail = patient.User.Email,
                    CreatedAt = patient.CreatedAt.ToString("yyyy-MM-dd"),
                    mode = PatientsTableMode.Default
                });
            }


            var response = DataTableHelper.CreateResponse(request, totalRecords, filteredRecords, patientsVm);



            return Json(response);
        }


        // GET: Patients/Details/5
        [Authorize(Roles = Roles.AdminAndReceptionistAndPatient)]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
                return NotFound();

            var patient = await _context.Patient
                .Include(p => p.User)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (patient == null)
                return NotFound();

            if (User.IsInRole("Patient"))
            {
                var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                if (patient.UserId != userId)
                    return Forbid();
            }

            return View(patient);
        }

        [Authorize(Roles = Roles.ReceptionistAndPatient)]
        public async Task<IActionResult> Create(string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            ViewData["SexOptions"] = EnumHelper.GetSelectList<Sex>();

            var existingPatient = await _context.Patient
                .FirstOrDefaultAsync(p => p.UserId == User.FindFirstValue(ClaimTypes.NameIdentifier));

            if (existingPatient != null)
            {
                return RedirectToAction(nameof(Edit), new { id = existingPatient.Id });
            }

            return View();
        }

        // POST: Patients/Create
        [HttpPost]
        [Authorize(Roles = Roles.Patient)]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(
            [Bind("Name,LastName,DateOfBirth,Sex,PhoneNumber,PeselNumber,Street,HouseNumber,Province,District,PostalCode,City")] Patient patient,
            [FromForm] string? returnUrl)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (userId == null) return Unauthorized();

            patient.UserId = userId;
            patient.User = await _context.Users.FindAsync(userId);
            patient.CreatedAt = DateTime.Now;

            ModelState.Remove("returnUrl"); // don't validate returnUrl
            if (ModelState.IsValid)
            {
                _context.Add(patient);
                await _context.SaveChangesAsync();

                if (!string.IsNullOrEmpty(returnUrl) && Url.IsLocalUrl(returnUrl))
                    return Redirect(returnUrl);

                return RedirectToAction(nameof(Edit), new { id = patient.Id });
            }

            ViewData["ReturnUrl"] = returnUrl;
            ViewData["SexOptions"] = EnumHelper.GetSelectList<Sex>();
            return View(patient);
        }

        // GET: Patients/Edit/5
        [Authorize(Roles = Roles.AdminAndReceptionistAndPatient)]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
                return NotFound();

            var patient = await _context.Patient.FindAsync(id);
            if (patient == null)
                return NotFound();


            if (User.IsInRole("Patient"))
            {
                var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                if (patient.UserId != userId)
                    return Forbid();
            }

            ViewData["SexOptions"] = EnumHelper.GetSelectList<Sex>();
            return View(patient);
        }

        // POST: Patients/Edit/5
        [HttpPost]
        [Authorize(Roles = Roles.AdminAndReceptionistAndPatient)]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,LastName,DateOfBirth,Sex,PhoneNumber,PeselNumber,Street,HouseNumber,Province,District,PostalCode,City")] Patient patient)
        {
            if (id != patient.Id)
                return NotFound();

            var existingPatient = await _context.Patient.AsNoTracking().FirstOrDefaultAsync(p => p.Id == id);
            if (existingPatient == null)
                return NotFound();


            if (User.IsInRole("Patient"))
            {
                var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                if (existingPatient.UserId != userId)
                    return Forbid();
            }

            patient.UserId = existingPatient.UserId;
            patient.User = await _context.Users.FindAsync(existingPatient.UserId);

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(patient);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PatientExists(patient.Id))
                        return NotFound();
                    else
                        throw;
                }

                // Jeśli pacjent edytował swoje dane → wróć do szczegółów
                if (User.IsInRole("Patient"))
                    return RedirectToAction(nameof(Details), new { id = patient.Id });

                return RedirectToAction(nameof(Index));
            }

            ViewData["SexOptions"] = EnumHelper.GetSelectList<Sex>();
            return View(patient);
        }

        private bool PatientExists(int id)
        {
            return _context.Patient.Any(e => e.Id == id);
        }

        // GET: Patients/CreateForUser
        [Authorize(Roles = Roles.AdminAndReceptionist)]
        public async Task<IActionResult> CreateForUser()
        {
            var usersInPatientRole = await _userManager.GetUsersInRoleAsync("Patient");
            var existingPatientUserIds = await _context.Patient.Select(p => p.UserId).ToListAsync();

            var availableUsers = usersInPatientRole
                .Where(u => !existingPatientUserIds.Contains(u.Id))
                .Select(u => new SelectListItem
                {
                    Value = u.Id,
                    Text = $"{u.UserName}"
                })
                .ToList();

            var viewModel = new PatientCardViewModel
            {
                AvailableUsers = availableUsers
            };

            ViewData["SexOptions"] = EnumHelper.GetSelectList<Sex>();
            return View(viewModel);
        }

        // POST: Patients/CreateForUser
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = Roles.AdminAndReceptionist)]
        public async Task<IActionResult> CreateForUser(PatientCardViewModel vm)
        {
            if (!ModelState.IsValid)
            {
                var usersInPatientRole = await _userManager.GetUsersInRoleAsync("Patient");
                var existingPatientUserIds = await _context.Patient.Select(p => p.UserId).ToListAsync();

                vm.AvailableUsers = usersInPatientRole
                    .Where(u => !existingPatientUserIds.Contains(u.Id))
                    .Select(u => new SelectListItem
                    {
                        Value = u.Id,

MedicalCenterRegistration/Views/Patients/Create.cshtml
@model MedicalCenterRegistration.Models.Patient

@{
    ViewData["Title"] = "Create";
}

<h1>Karta pacjenta</h1>
<h4 class="text-muted">Wypełnij kartę pacjenta, aby zacząć umawiać się na wizyty w naszej placówce.</h4>
<hr />
<form asp-action="Create" class="w-100" method="post">
    <div class="row gx-5 w-100">

        <div class="col-12 col-md-6 col-lg-4">
            <div class="mb-3">
                <label asp-for="Name" class="form-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label asp-for="LastName" class="form-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label asp-for="DateOfBirth" class="form-label"></label>
                <input asp-for="DateOfBirth" class="form-control" type="date" />
                <span asp-validation-for="DateOfBirth" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label asp-for="Sex" class="form-label"></label>
                @Html.DropDownListFor(m => m.Sex, ViewData["SexOptions"] as List<SelectListItem>, "-- Wybierz płeć --", new { @class = "form-control" })
                <span asp-validation-for="Sex" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label asp-for="PhoneNumber" class="form-label"></label>
                <input asp-for="PhoneNumber" class="form-control" maxlength="11" inputmode="numeric" pattern="\d{11}" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label asp-for="PeselNumber" class="form-label"></label>
                <input asp-for="PeselNumber" class="form-control" maxlength="11" inputmode="numeric" pattern="\d{11}" />
                <span asp-validation-for="PeselNumber" class="text-danger"></span>
                <div class="form-text">Nigdy nie udostępnimy nikomu twojego numeru pesel.</div>
            </div>
        </div>

        <div class="col-12 col-md-6 col-lg-4">
            <div class="mb-3">
                <label asp-for="Street" class="form-label"></label>
                <input asp-for="Street" class="form-control" />
                <span asp-validation-for="Street" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label asp-for="HouseNumber" class="form-label"></label>
                <input asp-for="HouseNumber" class="form-control" />
                <span asp-validation-for="HouseNumber" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label asp-for="Province" class="form-label"></label>
                <input asp-for="Province" class="form-control" />
                <span asp-validation-for="Province" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label asp-for="District" class="form-label"></label>
                <input asp-for="District" class="form-control" />
                <span asp-validation-for="District" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label asp-for="PostalCode" class="form-label"></label>
                <input asp-for="PostalCode" class="form-control" pattern="\d{2}-\d{3}" />
                <span asp-validation-for="PostalCode" class="text-danger"></span>
                <div class="form-text">Wprowadź kod w formacie 00-000.</div>
            </div>

            <div class="mb-3">
                <label asp-for="City" class="form-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
        </div>
    </div>
    @* this input allows controller to return to view that redirected user to patient creation after patient is created *@
    <input type="hidden" name="returnUrl" value="@ViewData["ReturnUrl"]" />
    <button type="submit" class="btn btn-primary mt-3">Zapisz</button>
</form>

@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}

<script>
    document.getElementById('PeselNumber').addEventListener('input', function (e) {
        this.value = this.value.replace(/\D/g, '').slice(0, 11);
    });
</script>

MedicalCenterRegistration/Views/Patients/CreateForUser.cshtml
@model MedicalCenterRegistration.Models.ViewModels.Patients.PatientCardViewModel

@{
    ViewData["Title"] = "Dodaj pacjenta dla użytkownika";
}


<h2>Dodaj kartę pacjenta dla użytkownika</h2>

<form asp-action="CreateForUser" method="post">
    <div class="form-group mb-3">
        <label asp-for="SelectedUserId" class="form-label"></label>
        <select asp-for="SelectedUserId" asp-items="Model.AvailableUsers" class="form-control">
            <option value="">-- wybierz użytkownika --</option>
        </select>
        <span asp-validation-for="SelectedUserId" class="text-danger"></span>
    </div>

    <div class="row">
        <div class="col-md-6">
            <div class="form-group mb-3">
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="form-group mb-3">
                <label asp-for="LastName"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>

            <div class="form-group mb-3">
                <label asp-for="PhoneNumber"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>

            <div class="form-group mb-3">
                <label asp-for="PeselNumber"></label>
                <input asp-for="PeselNumber" class="form-control" />
                <span asp-validation-for="PeselNumber" class="text-danger"></span>
            </div>

            <div class="form-group mb-3">
                <label asp-for="DateOfBirth"></label>
                <input asp-for="DateOfBirth" type="date" class="form-control" />
                <span asp-validation-for="DateOfBirth" class="text-danger"></span>
            </div>

            <div class="form-group mb-3">
                <label asp-for="Sex"></label>
                <select asp-for="Sex" asp-items="ViewBag.SexOptions" class="form-control"></select>
                <span asp-validation-for="Sex" class="text-danger"></span>
            </div>
        </div>

        <div class="col-md-6">
            <div class="form-group mb-3">
                <label asp-for="Street"></label>
                <input asp-for="Street" class="form-control" />
                <span asp-validation-for="Street" class="text-danger"></span>
            </div>

            <div class="form-group mb-3">
                <label asp-for="HouseNumber"></label>
                <input asp-for="HouseNumber" class="form-control" />
                <span asp-validation-for="HouseNumber" class="text-danger"></span>
            </div>

            <div class="form-group mb-3">
                <label asp-for="Province"></label>
                <input asp-for="Province" class="form-control" />
                <span asp-validation-for="Province" class="text-danger"></span>
            </div>

            <div class="form-group mb-3">
                <label asp-for="District"></label>
                <input asp-for="District" class="form-control" />
                <span asp-validation-for="District" class="text-danger"></span>
            </div>

            <div class="form-group mb-3">
                <label asp-for="PostalCode"></label>
                <input asp-for="PostalCode" class="form-control" />
                <span asp-validation-for="PostalCode" class="text-danger"></span>
            </div>

            <div class="form-group mb-3">
                <label asp-for="City"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
        </div>
    </div>

    <div class="mt-4">
        <button type="submit" class="btn btn-primary">Zapisz</button>
        <a asp-action="Index" class="btn btn-secondary ms-2">Anuluj</a>
    </div>
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

MedicalCenterRegistration/Views/Patients/Details.cshtml
@model MedicalCenterRegistration.Models.Patient

@{
    ViewData["Title"] = "Szczegóły Pacjenta";
}

<h1>Szczegóły Pacjenta</h1>

<div>
    <h4>Dane Pacjenta</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PeselNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PeselNumber)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DateOfBirth)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Sex)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Sex)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Street)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Street)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.HouseNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.HouseNumber)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Province)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Province)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.District)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.District)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PostalCode)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PostalCode)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>
    </dl>
</div>

<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id" class="btn btn-primary">Edytuj</a>
    <a asp-action="Index" class="btn btn-secondary">Powrót</a>
</div>

MedicalCenterRegistration/Views/Patients/Index.cshtml
@using MedicalCenterRegistration.Models.ViewModels.Patients

@{
    ViewData["Title"] = "Lista pacjentów";
}

<h1>Lista naszych pacjentów</h1>
<div class="mb-3">
    <a asp-action="CreateForUser" class="btn btn-primary">Przypisz kartę pacjenta</a>
</div>
<hr />

@await Html.PartialAsync("Patients/_PatientsTable")


<script>
    window.dataTableSSConfig = {
        ajaxUrl: '@Url.Action("GetPatients", "Patients")',
        columns: [
            { data: 'name' },
            { data: 'lastName' },
            { data: 'userEmail', name: "user.email" },
            { data: 'createdAt' },
            {
                data: 'id', // The data field must be the ID needed for the links
                orderable: false,
                searchable: false,
                render: function (data, type, row) {
                    return `<a href="/Patients/Details/${data}" class="btn btn-sm btn-outline-primary">Szczegóły</a>
                                        <a href="/Patients/Edit/${data}" class="btn btn-sm btn-outline-success">Edytuj</a>`;
                }
            }
        ]
    };
</script>