MedicalCenterRegistration/Models/ViewModels/VisitSummaries/CreateVisitSummaryViewModel.cs
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System.ComponentModel.DataAnnotations;
using MedicalCenterRegistration.Validation;

namespace MedicalCenterRegistration.Models.ViewModels.VisitSummaries
{
    public class CreateVisitSummaryViewModel
    {
        [Required(ErrorMessage = "Podsumowanie wizyty jest wymagane")]
        [Display(Name = "Podsumowanie wizyty i zalecenia")]
        [StringLength(2000)]
        public string Description { get; set; } = string.Empty;

        [Display(Name = "Załączniki")]
        [MaxFileCount(5, ErrorMessage = "Można dodać maksymalnie 5 plików.")]
        public List<IFormFile>? UploadedFiles { get; set; }
        public List<UserFile>? CurrentUserFiles { get; set; }

        public int VisitId { get; set; }
        public int Id { get; set; }
    }
}

MedicalCenterRegistration/Models/VisitSummary.cs
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;

namespace MedicalCenterRegistration.Models
{
    public class VisitSummary
    {
        public int Id { get; set; }
        public int VisitId { get; set; }
        [ValidateNever]
        public virtual Visit Visit { get; set; }

        [Required(ErrorMessage = "Podsumowanie wizyty jest wymagane")]
        [Display(Name = "Podsumowanie wizyty i zalecenia")]
        [StringLength(2000)]
        public string Description { get; set; } = string.Empty; // notes from doctor

        [Display(Name = "Załączniki")]
        public List<UserFile> Files { get; set; } = new();

        [Display(Name = "Data utworzenia")]
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

        [Display(Name = "Ostatnia aktualizacja")]
        public DateTime? UpdatedAt { get; set; }
    }
}

MedicalCenterRegistration/Controllers/UserFilesController.cs
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System.Security.Claims;
using MedicalCenterRegistration.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace MedicalCenterRegistration.Controllers
{
    public class UserFilesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public UserFilesController(ApplicationDbContext context)
        {
            _context = context;
        }


        [HttpGet]
        public IActionResult DownloadFile(string filePath, string fileName)
        {
            if (string.IsNullOrEmpty(filePath))
                return NotFound();

            var fullFilePath = Path.Combine(Directory.GetCurrentDirectory(), filePath);


            var fileInDb = _context.UserFile.Include(uf => uf.Owners).Where(UserFile => UserFile.FilePath == filePath).FirstOrDefault();
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);


            if (!System.IO.File.Exists(fullFilePath) || fileInDb == null)
                return NotFound();


            var ownerIds = fileInDb.Owners.Select(owner => owner.UserId).ToList();


            if (!ownerIds.Contains(userId))
            {
                return Unauthorized();
            }

            var contentType = "application/octet-stream";
            return PhysicalFile(fullFilePath, contentType, fileName);
        }

        private bool UserFileExists(int id)
        {
            return _context.UserFile.Any(e => e.Id == id);
        }
    }
}

MedicalCenterRegistration/Controllers/VisitsController.cs
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System.ComponentModel.DataAnnotations;
using System.Globalization;
using System.Security.Claims;
using Humanizer;
using MedicalCenterRegistration.Consts;
using MedicalCenterRegistration.Data;
using MedicalCenterRegistration.Enums;
using MedicalCenterRegistration.Helpers;
using MedicalCenterRegistration.Models;
using MedicalCenterRegistration.Models.ViewModels.Visits;
using MedicalCenterRegistration.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace MedicalCenterRegistration.Controllers
{
    public class VisitsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly PatientService _patientService;
        private readonly VisitsService _visitsService;
        private readonly ILogger<VisitsController> _logger;

        public VisitsController(ApplicationDbContext context, PatientService patientService, VisitsService visitsService, ILogger<VisitsController> logger)
        {
            _context = context;
            _patientService = patientService;
            _visitsService = visitsService;
            _logger = logger;
        }

        // GET: Visits
        [Authorize(Roles = Roles.Patient)]
        public async Task<IActionResult> Index()
        {

            var loggedInUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var visits = await _context.Visit
                    .Include(v => v.Doctor).ThenInclude(d => d.Image)
                    .Include(v => v.Patient)
                    .Include(v => v.VisitSchedule)
                    .Where(v => v.Patient.UserId == loggedInUserId)
                    .OrderByDescending(v => v.Id) // newest visits first
                    .ToListAsync();

            return View(visits);
        }


        // GET: AllVisits
        [Authorize(Roles = Roles.AdminAndReceptionist)]
        public async Task<IActionResult> AllVisits()
        {
            var applicationDbContext = _context.Visit
                .Include(v => v.Doctor)
                .Include(v => v.Patient)
                .Include(v => v.VisitSchedule)
                .OrderByDescending(v => v.Id); // newest visits first

            return View(await applicationDbContext.ToListAsync());
        }


        [Authorize(Roles = Roles.Doctor)]
        public async Task<IActionResult> DoctorVisits()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var visits = await _context.Visit
                .Include(v => v.Doctor)
                .Include(v => v.Patient)
                .Include(v => v.VisitSchedule)
                .Where(v => v.Doctor.UserId == userId)
                .OrderByDescending(v => v.Id) // newest visits first
                .ToListAsync();

            return View(visits);
        }

        // AJAX endpoint for DataTables to fetch visits data
        [HttpPost]
        [Authorize(Roles = Roles.AdminAndReceptionist)]
        public async Task<IActionResult> GetVisits()
        {
            var request = DataTableHelper.GetRequest(Request);
            var query = _context.Visit.AsQueryable();
            var recordsTotal = await query.CountAsync();

            query = query.Include(v => v.Doctor).Include(v => v.Patient).Include(v => v.VisitSchedule);

            //  search by patient's and doctor's info
            if (!string.IsNullOrEmpty(request.SearchValue))
            {
                query = query.Where
                    (u => u.Patient.Name.Contains(request.SearchValue) ||
                     u.Patient.LastName.Contains(request.SearchValue) ||
                     u.Doctor.Name.Contains(request.SearchValue) ||
                     u.Doctor.LastName.Contains(request.SearchValue) ||
                     u.Patient.PeselNumber.Contains(request.SearchValue)
                     );
            }


            var recordsFiltered = await query.CountAsync();

            query = query.ApplySorting(request);

            var visits = query
                .Skip(request.Start)
                .Take(request.Length)
            .ToList();

            var vm = new List<AdminReceptionistVisitViewModel>();

            var isReceptionist = User.IsInRole(Roles.Receptionist);

            foreach (var visit in visits)
            {
                var isCancellable = isReceptionist && 
                    visit.Status == Status.Pending &&
                    (visit.VisitSchedule.VisitDate > DateOnly.FromDateTime(DateTime.Now) ||
                     (visit.VisitSchedule.VisitDate == DateOnly.FromDateTime(DateTime.Now) && visit.VisitSchedule.VisitTimeStart > TimeOnly.FromDateTime(DateTime.Now)));

                vm.Add(new AdminReceptionistVisitViewModel
                {
                    Id = visit.Id,
                    Patient = "{0} {1}".FormatWith(visit.Patient.Name, visit.Patient.LastName),
                    Doctor = "{0} {1}".FormatWith(visit.Doctor.Name, visit.Doctor.LastName),
                    Date = visit.VisitSchedule.VisitDate,
                    Time = "{0} - {1}".FormatWith(visit.VisitSchedule.VisitTimeStart.ToString("HH:mm"), visit.VisitSchedule.VisitTimeEnd.ToString("HH:mm")),
                    VisitType = visit.VisitType,
                    VisitStatus = EnumHelper.GetDisplayName(visit.Status),
                    IsCancellable = isCancellable
                });
            }

            var response = DataTableHelper.CreateResponse(
                request,
                recordsTotal,
                recordsFiltered,
                vm
            );

            return Json(response);
        }



        [HttpGet]
        [Authorize(Roles = Roles.ReceptionistAndPatient)]
        public async Task<IActionResult> VisitsLimit()
        {
            return View();
        }


        //GET: ChoosePatient
        [HttpGet]
        [Authorize(Roles = Roles.Receptionist)]
        public async Task<IActionResult> ChoosePatient()
        {
            return View();
        }


        // GET: ChooseSpecializationType
        [HttpGet]
        [Authorize]
        public async Task<IActionResult> ChooseSpecializationType(int? patientId)
        {

            var userRole = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.Role)?.Value;
            var userId = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier)?.Value;
            bool hasPatientInfo;

            switch (userRole)
            {
                case Roles.Receptionist:
                    hasPatientInfo = await _patientService.HasPatientEntryByIdAsync(patientId);
                    if (!hasPatientInfo)
                    {
                        return RedirectToAction("CreateForUser", "Patients");
                    }
                    var hasPatientReachedVisitsLimit = await _visitsService.HasPatientReachedActiveVisitsLimit(patientId);
                    if (hasPatientReachedVisitsLimit)
                    {
                        return RedirectToAction(nameof(VisitsLimit));
                    }
                    break;
                case Roles.Patient:
                    hasPatientInfo = await _patientService.HasPatientEntryAsync(User);
                    if (!hasPatientInfo)
                    {
                        return RedirectToAction("Create", "Patients", new { returnUrl = Url.Action(nameof(ChooseSpecializationType)) });
                    }
                    var hasUserReachedVisitsLimit = await _visitsService.HasUserReachedActiveVisitsLimit(userId);
                    if (hasUserReachedVisitsLimit)
                    {
                        return RedirectToAction(nameof(VisitsLimit));
                    }
                    break;
                default:
                    return Forbid();
            }


            var specializations = await _context.DoctorSpecialization
                .GroupBy(ds => new { ds.Specialization.Id, ds.Specialization.Name })
                .Select(g => new SpecializationWithDoctorCount
                {
                    SpecializationId = g.Key.Id,
                    SpecializationName = g.Key.Name,
                    DoctorCount = g.Count()
                })
                .ToListAsync();


            var viewModel = new ChooseDoctorSpecializationViewModel
            {
                Specializations = specializations,
                patientId = patientId
            };

            return View(viewModel);
        }

        // POST: Visits
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SubmitSpecializationType(string specializationId, string? patientId)
        {
            if (string.IsNullOrEmpty(specializationId))
            {
                ModelState.AddModelError("", "Please select a visit type.");
                return View(nameof(ChooseSpecializationType));
            }

            TempData["SpecializationId"] = specializationId;
            TempData["PatientId"] = patientId;

            return RedirectToAction(nameof(Create));
        }



        // GET: Visits/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var visit = await _context.Visit
                .Include(v => v.Doctor).ThenInclude(d => d.Image)
                .Include(v => v.Patient)
                .Include(v => v.VisitSchedule)
                .Include(v => v.VisitSummary).ThenInclude(vs => vs.Files)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (visit == null)
            {
                return NotFound();
            }

MedicalCenterRegistration/Views/VisitSummaries/Create.cshtml
@model MedicalCenterRegistration.Models.ViewModels.VisitSummaries.CreateVisitSummaryViewModel

@{
    ViewData["Title"] = "Create";
}

<div class="mb-2">
    <a class="btn btn-outline-primary btn-xs" asp-controller="Visits" asp-action="DoctorVisits">
        <i class="bi bi-arrow-left-circle me-1"></i>
        Wróć do listy wizyt
    </a>
</div>

<h1>Dodaj podsumowanie wizyty</h1>
<h4 class="text-muted">Podsumuj wnioski z wizyty aby przekazać pacjentowi istotne informacje.</h4>
<hr />


<form asp-action="Create" method="post" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

    <div class="row mb-3">
        <div class="col-md-6">
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control" rows="5"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <div class="mb-3">
                <label class="form-label">Dodaj załączniki</label>
                <input multiple type="file" asp-for="UploadedFiles" id="fileInput" class="form-control" accept="image/*, .pdf" />
                <span asp-validation-for="UploadedFiles" class="text-danger"></span>
                <div class="form-text">Możliwe jest dodawanie obrazów, oraz plików .pdf</div>
            </div>
            <div id="fileListContainer" ** class="mt-3 mb-3">
            </div>

            <div class="form-group">
                <input type="submit" value="Dodaj podsumowanie" class="btn btn-primary" />
            </div>
        </div>
    </div>

    <div>
</form>




<script>
    // javascript to display added file's names
    document.addEventListener('DOMContentLoaded', function () {
        const fileInput = document.getElementById('fileInput');
        const fileListContainer = document.getElementById('fileListContainer');

        fileInput.addEventListener('change', function (event) {
            fileListContainer.innerHTML = '';

            const files = event.target.files;

            if (files.length > 0) {
                const ul = document.createElement('ul');

                ul.classList.add('list-group');
                ul.classList.add('pe-none')

                for (let i = 0; i < files.length; i++) {
                    const file = files[i];

                    const li = document.createElement('li');
                    const classes = ['list-group-item', 'badge', 'badge-pill', 'badge-secondary']

                    classes.forEach(cls => {
                        li.classList.add(cls);
                    });

                    li.textContent = file.name;

                    ul.appendChild(li);
                }

                fileListContainer.innerHTML = '<span>Wybrane pliki:</span>';
                fileListContainer.appendChild(ul);

            }
        });
    })
</script>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

MedicalCenterRegistration/Views/VisitSummaries/Edit.cshtml
@using MedicalCenterRegistration.Helpers
@model MedicalCenterRegistration.Models.ViewModels.VisitSummaries.CreateVisitSummaryViewModel

@{
    ViewData["Title"] = "Edytuj";
}

<div class="mb-2">
    <a class="btn btn-outline-primary btn-xs" asp-controller="Visits" asp-action="DoctorVisits">
        <i class="bi bi-arrow-left-circle me-1"></i>
        Wróć do listy wizyt
    </a>
</div>

<h1>Edytuj podsumowanie wizyty</h1>
<h4 class="text-muted">Podsumuj wnioski z wizyty aby przekazać pacjentowi istotne informacje.</h4>
<hr />


<form asp-action="Edit" asp-route-visitId="@Model.VisitId" method="post" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

    <input type="hidden" asp-for="Id" value="@Model.Id" />
    <div class="row mb-3">
        <div class="col-md-6">
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control" rows="5"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <div class="mb-3">
                <label class="form-label">Dodaj załączniki</label>
                <input multiple type="file" asp-for="UploadedFiles" id="fileInput" class="form-control" accept="image/*, .pdf" />
                <span asp-validation-for="UploadedFiles" class="text-danger"></span>
                <div class="form-text">Możliwe jest dodawanie obrazów, oraz plików .pdf</div>
            </div>
            <div id="fileListContainer" ** class="mt-3 mb-3">
            </div>

            <div class="alert alert-warning">Edycja załączników spowoduje usunięcie poprzednio dodanych załączników.</div>

            <div class="mb-3">
                <span>Aktualnie dodane załączniki:</span>
                @if (Model.CurrentUserFiles != null && Model.CurrentUserFiles.Any())
                {
                    <ul class="list-group">
                        @foreach (var file in Model.CurrentUserFiles)
                        {
                            <li class="list-group-item">
                                <a href="@Url.Action("DownloadFile", "UserFiles", new { filePath = file.FilePath, fileName = file.FileName })" target="_blank">
                                    @file.FileName
                                </a>
                            </li>
                        }
                    </ul>
                }
                else
                {
                    <span>Brak załączników</span>
                }
            </div>


            <div class="form-group">
                <input type="submit" value="Dodaj podsumowanie" class="btn btn-primary" />
            </div>
        </div>
    </div>

    <div>
</form>




<script>
    // javascript to display added file's names
    document.addEventListener('DOMContentLoaded', function () {
        const fileInput = document.getElementById('fileInput');
        const fileListContainer = document.getElementById('fileListContainer');

        const listUploadedFiles = (files) => {
            fileListContainer.innerHTML = '';

            if (files.length > 0) {
                const ul = document.createElement('ul');

                ul.classList.add('list-group');
                ul.classList.add('pe-none')

                for (let i = 0; i < files.length; i++) {
                    const file = files[i];

                    const li = document.createElement('li');
                    const classes = ['list-group-item', 'badge', 'badge-pill', 'badge-secondary']

                    classes.forEach(cls => {
                        li.classList.add(cls);
                    });

                    li.textContent = file.name.substr(0, 30).concat('...')

                    ul.appendChild(li);
                }

                fileListContainer.innerHTML = '<span>Wybrane pliki:</span>';
                fileListContainer.appendChild(ul);

            }

        }

        const initialFiles = fileInput.files;
        listUploadedFiles(initialFiles);

        fileInput.addEventListener('change', function (event) {
            const files = event.target.files;
            listUploadedFiles(files)
        });
    })
</script>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}